export const LOGGED_USER_ID = 1

export const MESSAGING_TEXT = {
  common: {
    loading: 'Loading...',
    close: 'Close',
    cancel: 'Cancel',
    retry: 'Try again',
    create: 'Create',
    creating: 'Creating...',
  },
  header: {
    brandName: 'Leboncoin',
    pageTitle: 'Messages',
    pageDescription: 'Leboncoin messaging: view and reply to your conversations.',
    newConversation: 'New conversation',
  },
  conversations: {
    navigationLabel: 'Conversations',
    title: 'Conversations',
    emptyTitle: 'No conversations',
    emptyDescription: 'You do not have any conversations yet.',
    itemLabel: 'Conversation',
    selectedTitle: 'No conversation selected',
    selectedDescription: 'Select a conversation to view its messages.',
    back: 'Back',
  },
  messages: {
    listLabel: 'Messages',
    loading: 'Loading messages...',
    emptyTitle: 'No messages',
    emptyDescription: 'This conversation does not contain any messages yet.',
    sentLabel: 'Sent message',
    receivedLabel: 'Received message',
    composerLabel: 'Your message',
    composePlaceholder: 'Write a message',
    send: 'Send',
    sending: 'Sending...',
  },
  newConversation: {
    title: 'New conversation',
    recipientLabel: 'Recipient',
    recipientLoading: 'Loading...',
    recipientPlaceholder: 'Select a user',
  },
  errors: {
    conversationsLoadFallback: 'Failed to load conversations.',
    messagesLoadFallback: 'Failed to load messages.',
    usersLoadFallback: 'Users could not be loaded.',
    conversationCreateFallback: 'The conversation could not be created.',
    sendMessage: 'The message could not be sent. Check your connection and try again.',
    duplicateConversation: 'A conversation with this user already exists.',
    invalidRequest: 'The request is invalid.',
    resourceNotFound: 'The requested resource could not be found.',
    serviceUnavailable: 'The service is temporarily unavailable.',
    serviceFailure: 'The service encountered a problem.',
    connectionUnavailable: 'The connection to the service is unavailable.',
    invalidResponse: 'The service response is invalid.',
    invalidMessage: 'The message is invalid.',
    invalidConversation: 'The conversation is invalid.',
    invalidUserId: 'The user ID is invalid.',
    invalidRecipient: 'The recipient is invalid.',
    invalidConversationId: 'The conversation ID is invalid.',
    invalidAuthorId: 'The author ID is invalid.',
    invalidMessageContent: 'The message content is invalid.',
    invalidTimestamp: 'The message timestamp is invalid.',
    invalidConversationsResponse: 'The conversations response is invalid.',
    invalidUsersResponse: 'The users response is invalid.',
    invalidMessagesResponse: 'The messages response is invalid.',
    invalidConversationCreationResponse:
      'The conversation creation response is invalid.',
    invalidMessageCreationResponse: 'The message creation response is invalid.',
    conversationNotCreated: 'The conversation could not be created.',
    messageNotCreated: 'The message could not be created.',
  },
} as const
